### ISSUE TITLE
Repository of the package flython

### ISSUE THREAD

**Issue by guyluz11** [amahta/clipboard_ocr#1]
I've just stumbled upon your package [flython](https://pub.dev/packages/flython) which I think is quite genius but I haven't start working with it yet.

I can't find the repository of this package, all the links that you have posted arrive here.
Pub.dev have a homepage link which brings to the article but not a "Repository (GitHub)" link like most of the packages in pub.dev

In order for developers to use and trust the package they need to see it's code.
Seeing the code let them know that they can open PR for new features open issues and fork it if the maintainer stop maintaining the package (and their project is based on it)

The only link on the pub.dev is "Homepage"

What I see

![Screenshot_20221103-084122_Firefox](https://user-images.githubusercontent.com/9304740/199661242-a977cddc-1ef8-443b-b842-ed87e7846588.jpg)

What I am expecting to see

![Screenshot_20221103_084434](https://user-images.githubusercontent.com/9304740/199661262-9bfc4249-b55e-431f-b2de-8f492940c8b9.jpg)

**Comment by amahta** [comment]
Hi @guyluz11,
Sorry for the late reply.
You make good points, and I totally agree with all of them.
Flython repository not being on GitHub is probably just because I got lazy setting up its page. Can't remember to be honest :) Busy days.
I'll make sure to put it on GitHub as soon as I get a chance.

In the meantime, you can look at the code after adding Flython to your project and running `pub get`.
Just running `pub get` is usually harmless.

After getting the code, you can find the code in dart cache.
On Windows, it's located somewhere similar to the path below:
```
C:\Users\<USER>\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flython-0.1.3
```

Cheers and good luck!

**Comment by guyluz11** [comment]
Thanks :D
